# Generated by Django 4.1.7 on 2024-01-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'verbose_name_plural': 'Todos'},
        ),
        migrations.AddField(
            model_name='todos',
            name='status',
            field=models.CharField(choices=[('CO', 'Completed'), ('PE', 'Pending'), ('IN', 'In-progress')], default='PE', max_length=2),
        ),
    ]
