name: Deploy to aws ec2
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Add SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GH_PEM_KEY }}
          known_hosts: 'github.com'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd p*/p*
            git pull
            source .venv/bin/activate
            pip install -r requirements.txt
            ./manage.py makemigrations
            ./manage.py migrate
            sudo systemctl restart penfolio
            sudo systemctl reload nginx
        env:
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
